# This is the CI/CD pipeline for your Python backend.
# It automatically builds and deploys the backend to Google Cloud Run
# whenever you push changes to the 'backend' folder on the 'main' branch.

name: Deploy Backend to Cloud Run

on:
  push:
    branches: [ "main" ]
    # CORRECTED: 'paths' is now correctly indented under 'push'.
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and Push Docker Image
        run: |-
          gcloud auth configure-docker gcr.io --quiet
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/music-backend-image:latest ./backend
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/music-backend-image:latest

      - name: Deploy to Cloud Run with Secrets
        uses: google-github-actions/deploy-run@v2
        with:
          service: music-backend-service
          region: us-central1
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/music-backend-image:latest
          # CORRECTED: 'secrets' is now a multiline string (using |-), which is the correct format for this action.
          secrets: |-
            MONGO_URL=projects/${{ secrets.GCP_PROJECT_ID }}/secrets/MONGO_URL:latest
            DB_NAME=projects/${{ secrets.GCP_PROJECT_ID }}/secrets/DB_NAME:latest
            SECRET_KEY=projects/${{ secrets.GCP_PROJECT_ID }}/secrets/SECRET_KEY:latest