# .github/workflows/frontend-deploy.yml

name: Deploy Frontend to Cloud Run

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    # Add permissions for Workload Identity Federation
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/175236630501/locations/global/workloadIdentityPools/moon-music-wif-pool/providers/github-provider'
          service_account: "github-actions-deployer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
      
      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          # --- THIS IS THE CORRECTED LINE ---
          # Set the context to the 'frontend' sub-directory
          context: ./frontend
          push: true
          tags: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/music-library-images/music-frontend-image:latest
          # Pass the backend URL as a build-time argument to Docker
          build-args: |
            REACT_APP_BACKEND_URL=${{ secrets.BACKEND_URL }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: music-frontend-service
          region: us-central1
          # Point to the image that was just pushed
          image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/music-library-images/music-frontend-image:latest
          # The REACT_APP_BACKEND_URL is now baked into the container,
          # so the 'env_vars' section is not needed for this variable.