name: Deploy Frontend to Cloud Run

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # CORRECTED: Pinned to a specific commit hash for v2
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@d8813a34a87713203f16b2513364f77c3886b6ac # Pinned to v2.1.2

      # CORRECTED: Pinned to a specific commit hash for v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@d682054a72d242167ecf45c7d2427f71f8450c25 # Pinned to v2.1.0

      - name: Build and Push Docker Image
        run: |-
          gcloud auth configure-docker gcr.io --quiet
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/music-frontend-image:latest ./frontend
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/music-frontend-image:latest

      # CORRECTED: Pinned to a specific commit hash for v2
      - name: Deploy to Cloud Run with Backend URL
        uses: google-github-actions/deploy-run@a50c39f15538e1e32d1f705b1c55b682b13c1f23 # Pinned to v2.0.0
        with:
          service: music-frontend-service
          region: us-central1
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/music-frontend-image:latest
          env-vars: |-
            BACKEND_URL=${{ secrets.BACKEND_URL }}
