# .github/workflows/frontend-deploy.yml

name: Deploy Frontend to Cloud Run 

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    # Add permissions for Workload Identity Federation
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/175236630501/locations/global/workloadIdentityPools/moon-music-wif-pool/providers/github-provider'
          # Using double quotes to ensure the secret is expanded
          service_account: "github-actions-deployer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Push Docker Image to Artifact Registry
        run: |-
          # Enable Docker authentication for Artifact Registry
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
          
          # Build and tag the image with the full Artifact Registry path
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcr.io/music-frontend-image:latest ./frontend
          
          # Push the image
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcr.io/music-frontend-image:latest

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: music-frontend-service
          region: us-central1
          # Point to the image in Artifact Registry
          image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcr.io/music-frontend-image:latest
          env_vars: |-
            BACKEND_URL=${{ secrets.BACKEND_URL }}
