# This is the CI/CD pipeline for your React frontend.
# It automatically builds and deploys the frontend to Google Cloud Run
# whenever you push changes to the 'frontend' folder on the 'main' branch.

name: Deploy Frontend to Cloud Run

on:
  push:
    branches: [ "main" ]
    # CORRECTED: 'paths' is now correctly indented under 'push'.
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and Push Docker Image
        run: |-
          gcloud auth configure-docker gcr.io --quiet
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/music-frontend-image:latest ./frontend
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/music-frontend-image:latest

      - name: Deploy to Cloud Run with Backend URL
        uses: google-github-actions/deploy-run@v2
        with:
          service: music-frontend-service
          region: us-central1
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/music-frontend-image:latest
          # CORRECTED: 'env-vars' is now a multiline string (using |-), which is the correct format for this action.
          env-vars: |-
            BACKEND_URL=${{ secrets.BACKEND_URL }}
