name: Deploy Frontend to Cloud Run

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    # Add permissions for the keyless authentication to work
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- THIS IS THE UPDATED STEP ---
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          # Replace <YOUR_PROJECT_NUMBER> with your actual project number
          workload_identity_provider: 'projects/175236630501/locations/global/workloadIdentityPools/moon-music-wif-pool/providers/github-provider'
          service_account: 'github-actions-deployer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and Push Docker Image
        run: |-
          gcloud auth configure-docker gcr.io --quiet
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/music-frontend-image:latest ./frontend
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/music-frontend-image:latest

      - name: Deploy to Cloud Run with Backend URL
        uses: google-github-actions/deploy@v2
        with:
          service: music-frontend-service
          region: us-central1
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/music-frontend-image:latest
          env-vars: |-
            BACKEND_URL=${{ secrets.BACKEND_URL }}
