# .github/workflows/frontend-deploy.yml

name: Deploy Frontend to Cloud Run 

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    # Add permissions for Workload Identity Federation
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/175236630501/locations/global/workloadIdentityPools/moon-music-wif-pool/providers/github-provider'
          # Using double quotes to ensure the secret is expanded
          service_account: "github-actions-deployer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/music-library-images/music-frontend-image:latest
          # --- ADD THIS BLOCK ---
          build-args: |
            REACT_APP_BACKEND_URL=${{ secrets.BACKEND_URL }}


      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: music-frontend-service
          region: us-central1
          image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/music-library-images/music-frontend-image:latest
          # This env_vars block is no longer needed here for the frontend, 
          # because the value is now baked into the static files.
